2021-07-22 14:22:57,273 ERROR: Exception on /user/Rarf [GET][in /home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ruairi/Flask_MegaTutorial/app/main/routes.py", line 59, in user
    return render_template("user.html", user=user, posts=posts.items,
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ruairi/Flask_MegaTutorial/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/ruairi/Flask_MegaTutorial/app/templates/base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/home/ruairi/Flask_MegaTutorial/app/templates/base.html", line 48, in block 'content'
    {% block app_content %}{% endblock%}
  File "/home/ruairi/Flask_MegaTutorial/app/templates/user.html", line 13, in block 'app_content'
    <p><a href = "{{ url_for('edit_profile') }}">Edit your profile</a></p>
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'edit_profile'. Did you mean 'main.edit_profile' instead?
2021-07-22 14:23:47,265 INFO: Microblog startup[in /home/ruairi/Flask_MegaTutorial/app/__init__.py:75]
2021-07-22 14:23:55,973 ERROR: Exception on /translate [POST][in /home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ruairi/Flask_MegaTutorial/app/main/routes.py", line 131, in translate_text
    return jsonify({"text": translate(request.form["text"],
  File "/home/ruairi/Flask_MegaTutorial/app/translate.py", line 6, in translate
    if "MS_TRANSLATOR_KEY" not in app.config or \
NameError: name 'app' is not defined
2021-07-22 14:25:54,890 INFO: Microblog startup[in /home/ruairi/Flask_MegaTutorial/app/__init__.py:75]
2021-07-22 14:26:06,629 ERROR: Exception on /translate [POST][in /home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ruairi/Flask_MegaTutorial/app/main/routes.py", line 131, in translate_text
    return jsonify({"text": translate(request.form["text"],
  File "/home/ruairi/Flask_MegaTutorial/app/translate.py", line 10, in translate
    subscription_key = app.config['MS_TRANSLATOR_KEY']
NameError: name 'app' is not defined
2021-07-22 14:26:26,909 INFO: Microblog startup[in /home/ruairi/Flask_MegaTutorial/app/__init__.py:75]
2021-07-22 14:27:44,668 INFO: Microblog startup[in /home/ruairi/Flask_MegaTutorial/app/__init__.py:75]
2021-07-22 14:30:54,407 INFO: Microblog startup[in /home/ruairi/Flask_MegaTutorial/app/__init__.py:75]
2021-07-22 14:31:07,606 INFO: Microblog startup[in /home/ruairi/Flask_MegaTutorial/app/__init__.py:75]
2021-07-22 15:03:22,506 INFO: Microblog startup[in /home/ruairi/Flask_MegaTutorial/app/__init__.py:75]
2021-07-22 15:09:43,505 INFO: Microblog startup[in /home/ruairi/Flask_MegaTutorial/app/__init__.py:75]
2021-07-22 15:11:05,606 INFO: Microblog startup[in /home/ruairi/Flask_MegaTutorial/app/__init__.py:75]
